spring:
  application:
    name: pix
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: pix
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pix?useUnicode=true&characterEncoding=UTF-8
  jpa:
    generate-ddl: on
    open-in-view: on
    show-sql: on
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      ddl-auto: create-drop
      defer-datasource-initialization: true
    h2:
    console:
      enabled: on
      path: /h2
  sql:
    init:
      platform: h2
      mode: always

server:
  port: 9090
  servlet:
    context-path: /pix

#spring:
#  application:
#    name: pix
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: pix
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/pix
#  jpa:
#    generate-ddl: on
#    open-in-view: on
#    show-sql: on
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
